services:
  postgresql-db:
    image: postgres:14.15-alpine3.21
    container_name: postgresql-db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_VOLUME}:/var/lib/postgresql/data
