services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ${TRANSMISSION_CONFIG}:/config
      - ${TRANSMISSION_DOWNLOADS}:/downloads
      - ${TRANSMISSION_WATCH}:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp