services:
  minidlna:
    image: vladgh/minidlna
    container_name: minidlna
    restart: unless-stopped
    network_mode: host
    env_file:
      - .env
    volumes:
      - ${MINIDLNA_VOLUME}:/media/video
    