services:
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      - TZ=America/La_Paz
      - WEBPASSWORD=raspberry
    volumes:
      - ${PIHOLE_VOLUMES}:/etc/pihole
      - ${PIHOLE_DNSMASQ_VOLUMES}:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN

